### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ni-ka** [Chadsr/NordVPN-NetworkManager#132]
I get this exception when entering my credentials (manjaro, installed via yay -S nordnm)

[INFO] [nordnm.credentials]: Attempting to verify credentials...
Traceback (most recent call last):
  File "/usr/bin/nordnm", line 11, in <module>
    load_entry_point('nordnm==0.6.1', 'console_scripts', 'nordnm')()
  File "/usr/lib/python3.7/site-packages/nordnm/__main__.py", line 26, in main
    nordnm.NordNM()
  File "/usr/lib/python3.7/site-packages/nordnm/nordnm.py", line 202, in __init__
    self.setup()
  File "/usr/lib/python3.7/site-packages/nordnm/nordnm.py", line 315, in setup
    self.credentials = CredentialsHandler(paths.CREDENTIALS)
  File "/usr/lib/python3.7/site-packages/nordnm/credentials.py", line 21, in __init__
    self.save_new_credentials()  # Prompt for credentials
  File "/usr/lib/python3.7/site-packages/nordnm/credentials.py", line 68, in save_new_credentials
    if nordapi.verify_user_credentials(username, password):
  File "/usr/lib/python3.7/site-packages/nordnm/nordapi.py", line 99, in verify_user_credentials
    return validate_user_token(token_json, password)
  File "/usr/lib/python3.7/site-packages/nordnm/nordapi.py", line 80, in validate_user_token
    token = token_json['token']
TypeError: 'NoneType' object is not subscriptable

**Comment by premma** [comment]
same problem here. 
```
[INFO] Attempting to verify credentials...
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/nordnm", line 11, in <module>
    load_entry_point('nordnm==0.7.1', 'console_scripts', 'nordnm')()
  File "/usr/lib64/python3.6/site-packages/nordnm/__main__.py", line 37, in main
    nordnm.NordNM()
  File "/usr/lib64/python3.6/site-packages/nordnm/nordnm.py", line 202, in __init__
    self.setup()
  File "/usr/lib64/python3.6/site-packages/nordnm/nordnm.py", line 316, in setup
    self.credentials = CredentialsHandler(paths.CREDENTIALS)
  File "/usr/lib64/python3.6/site-packages/nordnm/credentials.py", line 21, in __init__
    self.save_new_credentials()  # Prompt for credentials
  File "/usr/lib64/python3.6/site-packages/nordnm/credentials.py", line 67, in save_new_credentials
    if nordapi.verify_user_credentials(username, password):
  File "/usr/lib64/python3.6/site-packages/nordnm/nordapi.py", line 99, in verify_user_credentials
    return validate_user_token(token_json, password)
  File "/usr/lib64/python3.6/site-packages/nordnm/nordapi.py", line 80, in validate_user_token
    token = token_json['token']
TypeError: 'NoneType' object is not subscriptable
```
nordnm version 0.7.1, installed through gentoo layman "panther"

**Comment by SeanDHeath** [comment]
Same here - nordnm 0.6.1 installed on Debian 10.2 using pip3.

**Comment by Chadsr** [comment]
Sorry for the delay. It seems that NordVPN overhauled their API. Their API isn't public and I don't really have the time or motivation to reverse engineer it right now.. (I don't use NordVPN any more).

So unfortunately this will have to stay open until I or someone else more motivated has the time to pick through their private API again...

**Comment by evs-ch** [comment]
POST seems to be what's needed here now:

```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"username": "youremail", "password": "yourpassword"}' \
  https://api.nordvpn.com/v1/users/tokens
```

There's also `/v1/users/tokens/renew`, but I guess we won't need this for nordnm.

If no one else gets around to it, I'll see that I can get this working again in the next few days and submit a PR; seems like most other API things stayed the same, so it should be not too much work.

**Comment by WieFel** [comment]
Same here, using nordnm 0.6.1 on Manjaro Linux (Arch)
