### ISSUE TITLE
can't work after python packages update with pacman

### ISSUE THREAD

**Issue by peter7764** [Chadsr/NordVPN-NetworkManager#134]
`Traceback (most recent call last):
  File "/usr/bin/nordnm", line 11, in <module>
    load_entry_point('nordnm==0.6.1', 'console_scripts', 'nordnm')()
  File "/usr/lib/python3.8/site-packages/nordnm/__main__.py", line 26, in main
    nordnm.NordNM()
  File "/usr/lib/python3.8/site-packages/nordnm/nordnm.py", line 218, in __init__
    self.sync(args.update_configs, args.preserve_vpn, args.slow_mode)
  File "/usr/lib/python3.8/site-packages/nordnm/nordnm.py", line 396, in sync
    if self.sync_servers(preserve_vpn, slow_mode):
  File "/usr/lib/python3.8/site-packages/nordnm/nordnm.py", line 635, in sync_servers
    best_servers, num_success = benchmarking.get_best_servers(valid_server_list, ping_attempts, valid_protocols, valid_categories, slow_mode)
  File "/usr/lib/python3.8/site-packages/nordnm/benchmarking.py", line 102, in get_best_servers
    pool = multiprocessing.Pool(num_processes, maxtasksperchild=1)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 276, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files`

**Comment by lsfxz** [comment]
I'm not entirely sure how to "cleanly" handle this.

I get this on arch as well, when not "slowly" syncing. One can work around it by setting `ulimit -n 2048` (or something higher) in the shell before running nordnm.

There are checks in `benchmarking.py` which should prevent this from happening, but for some reason it does not work anymore.

A dirty workaround would be something like:

```diff
diff --git a/nordnm/benchmarking.py b/nordnm/benchmarking.py
index 51e8a2a..b5c48df 100644
--- a/nordnm/benchmarking.py
+++ b/nordnm/benchmarking.py
@@ -69,7 +69,9 @@ def get_num_processes(num_servers):
     # Since each process is not resource heavy and simply takes time waiting for pings, maximise the number of processes (within constraints of the current configuration)
  
     # Maximum open file descriptors of current configuration
-    soft_limit, _ = resource.getrlimit(resource.RLIMIT_NOFILE)
+    soft_limit, hard_limit = resource.getrlimit(resource.RLIMIT_NOFILE)
+
+    resource.setrlimit(resource.RLIMIT_NOFILE, (soft_limit * 2, hard_limit))
  
     # Find how many file descriptors are already in use by the parent process
     ppid = os.getppid()
```
and probably at least a quick check before it, like `if soft_limit <= 1024:`, but I'm not entirely sure if it would be advisable to set the soft_limit without asking the user.

Maybe someone else could look into why the calculation of the remaining limit doesn't work anymore instead.

In the meantime, slow syncing should always still work.
