### ISSUE TITLE
verify credentials error

### ISSUE THREAD

**Issue by originalnickname** [Chadsr/NordVPN-NetworkManager#139]
I installed with yay in AUR

I get this error on verify credentials:
`

[INFO] [nordnm.credentials]: Attempting to verify credentials... Traceback (most recent call last): File "/usr/bin/nordnm", line 11, in <module> load_entry_point('nordnm==0.6.1', 'console_scripts', 'nordnm')() File "/usr/lib/python3.8/site-packages/nordnm/__main__.py", line 26, in main nordnm.NordNM() File "/usr/lib/python3.8/site-packages/nordnm/nordnm.py", line 202, in __init__ self.setup() File "/usr/lib/python3.8/site-packages/nordnm/nordnm.py", line 315, in setup self.credentials = CredentialsHandler(paths.CREDENTIALS) File "/usr/lib/python3.8/site-packages/nordnm/credentials.py", line 21, in __init__ self.save_new_credentials() # Prompt for credentials File "/usr/lib/python3.8/site-packages/nordnm/credentials.py", line 68, in save_new_credentials if nordapi.verify_user_credentials(username, password): File "/usr/lib/python3.8/site-packages/nordnm/nordapi.py", line 99, in verify_user_credentials return validate_user_token(token_json, password) File "/usr/lib/python3.8/site-packages/nordnm/nordapi.py", line 80, in validate_user_token token = token_json['token'] TypeError: 'NoneType' object is not subscriptable`

**Comment by zion2k** [comment]
Same here...
Manjaro (KDE) + AUR install of NordNM

**Comment by rojnwa** [comment]
Same
installed on Arch (AUR)

**Comment by lsfxz** [comment]
There's also a nordnm-git package there: https://aur.archlinux.org/packages/nordnm-git

You could try that one, until a regular release is made again.

Disclaimer: I put that package there :)
