### ISSUE TITLE
problem with configparser.py in version 0.5.0

### ISSUE THREAD

**Issue by veryrad** [Chadsr/NordVPN-NetworkManager#87]
After upgrading to version 0.5.0 I get the following error when I use `sync -a` to establish a connection:
```
Traceback (most recent call last):
   File "/usr/lib/python3.6/configparser.py", line 1138, in _unify_values
     sectiondict = self._sections[section]
 KeyError: 'DNS'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/bin/nordnm", line 11, in <module>
     load_entry_point('nordnm==0.5.0', 'console_scripts', 'nordnm')()
   File "/usr/lib/python3.6/site-packages/nordnm/__main__.py", line 16, in main
     nordnm.NordNM()
   File "/usr/lib/python3.6/site-packages/nordnm/nordnm.py", line 209, in __init__
     self.sync(args.update_configs, args.preserve_vpn, args.slow_mode)
   File "/usr/lib/python3.6/site-packages/nordnm/nordnm.py", line 380, in sync
     if self.sync_servers(preserve_vpn, slow_mode):
   File "/usr/lib/python3.6/site-packages/nordnm/nordnm.py", line 539, in sync_servers
     dns_list = self.settings.get_custom_dns_servers()
   File "/usr/lib/python3.6/site-packages/nordnm/settings.py", line 135, in get_custom_dns_servers
     custom_dns = self.settings.get('DNS', 'custom-dns-servers')
   File "/usr/lib/python3.6/configparser.py", line 781, in get
     d = self._unify_values(section, vars)
   File "/usr/lib/python3.6/configparser.py", line 1141, in _unify_values
     raise NoSectionError(section)
 configparser.NoSectionError: No section: 'DNS'
```
I've tried a few configuations and this happends every time, which renders nordnm pretty much unusable.

**Comment by veryrad** [comment]
I dug into your release notes and saw the custom DNS settings. After running a fresh `update --settings` the issue has been resolved. Just a heads up that if you upgrade to the new release and don't run update, you may get some breakage.
