### ISSUE TITLE
Error after updating to v0.5.0

### ISSUE THREAD

**Issue by leedaz** [Chadsr/NordVPN-NetworkManager#88]
Hi, after updating to new version, I'm getting these messages in terminal. Any idea ? 
I've downgraded to v0.4.0 and all is working again. Thanks.

[INFO] [nordnm.nordnm]: Configuration files already up-to-date.
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'DNS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/nordnm", line 11, in <module>
    load_entry_point('nordnm==0.5.0', 'console_scripts', 'nordnm')()
  File "/usr/lib/python3.6/site-packages/nordnm/__main__.py", line 16, in main
    nordnm.NordNM()
  File "/usr/lib/python3.6/site-packages/nordnm/nordnm.py", line 209, in __init__
    self.sync(args.update_configs, args.preserve_vpn, args.slow_mode)
  File "/usr/lib/python3.6/site-packages/nordnm/nordnm.py", line 380, in sync
    if self.sync_servers(preserve_vpn, slow_mode):
  File "/usr/lib/python3.6/site-packages/nordnm/nordnm.py", line 539, in sync_servers
    dns_list = self.settings.get_custom_dns_servers()
  File "/usr/lib/python3.6/site-packages/nordnm/settings.py", line 135, in get_custom_dns_servers
    custom_dns = self.settings.get('DNS', 'custom-dns-servers')
  File "/usr/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'DNS'

**Comment by Chadsr** [comment]
I made a rather silly mistake whilst introducing a new setting. It will be patched asap, but for now running 'nordnm update --settings' will fix this.

**Comment by Chadsr** [comment]
A patch release (v0.5.1, bc15cc0) is on its way and fixes this without needing to update your settings.

**Comment by leedaz** [comment]
Upgraded now to v0.5.1 and all sorted. Many thanks for this great piece of software.

**Comment by Chadsr** [comment]
Good to hear and thank you! I will close this issue now, since it should no longer be a problem.
